version: '3.7'
services: 
    backend:
        container_name: backend
        build: 
            context: ./backend
            dockerfile: ./docker/dev/Dockerfile
        ports: 
            - 8001:80
        volumes: 
            - backend-sync:/var/www/app
    frontend:
        container_name: frontend
        build: 
            context: ./frontend
            dockerfile: ./docker/dev/Dockerfile
        ports: 
            - 8082:8080
        volumes: 
            - frontend-sync:/app
        command: "/bin/sh -c 'npm run serve'"
        # env_file: ./backend/.env
    db:
        volumes:
            - boca-new-db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
volumes:
    boca-new-db-data:
    frontend-sync:
        external: true
    backend-sync:
        external: true