version: '3.7'
services: 
    backend:
        container_name: backend
        privileged: true
        image: jvfazolo/algochallenger-backend
#        build: 
#            context: ./backend
#            dockerfile: ./docker/Dockerfile
        volumes:
            - ~/PrivateProjects/boca-testes/boca-volume:/var/www/app/storage
        depends_on: 
            - db
        deploy:
#           mode: global
#           placement:
#             constraints: [node.role == manager]
           replicas: 1
           update_config:
             parallelism: 2
#           restart_policy:
#             condition: on-failure
           resources:
             limits:
               cpus: '1'
               memory: 512M
        ports: 
            - 8001:80
        environment: 
            - DB_CONNECTION=pgsql
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - DB_PORT=5432
            - DB_DATABASE=boca
            - APP_NAME=Boca
            - LOG_CHANNEL=daily
            - DB_USERNAME=boca
            - APP_ENV=local
            - DB_PASSWORD=boca
            - DB_HOST=db
            - JWT_SECRET=UiUT2Dd8EwuiHpEFKsf93k945OTipS8uZb0gIl7PnwiVUIZv37yf5puWF0S5qHQx
            - APP_KEY=iUT2Dd8EwuiHpEFKs 
    frontend:
        container_name: frontend
        privileged: true
        image: jvfazolo/algochallenger-frontend
 #       build: 
 #           context: ./frontend
 #           dockerfile: ./docker/Dockerfile
        deploy:
           mode: global
#           placement:
#              constraints: [node.role == manager]
           resources:
              limits:
                 cpus: '1'
                 memory: 1024M
        environment: 
            - VUE_APP_BACKEND_URL=http://localhost:8001/api
        ports: 
            - 8181:80
        depends_on: 
            - backend

    db:
        image: postgres:12
        privileged: true
        container_name: boca-postgres
        environment: 
            - POSTGRES_PASSWORD=boca
            - POSTGRES_USER=boca
       # healthcheck:
       #     test: ["CMD-SHELL", "pg_isready -U postgres"]
       #     interval: 10s
       #     timeout: 5s
       #     retries: 5
        deploy:
#           mode: global
#           placement:
#             constraints: [node.role == worker]
           resources:
             limits:
               cpus: '1'
               memory: 1024M

    boca-jail:
        image: jvfazolo/boca-jail
        privileged: true
        container_name: boca-jail
        deploy:
#           mode: global
#           placement:
#              constraints: [node.role == worker]
           replicas: 4
           update_config:
               parallelism: 1
               delay: 10s
       #    restart_policy:
       #        condition: on-failure
           resources:
             limits:
               cpus: '1'
               memory: 512M
        environment: 
            - API_URL=http://backend/api
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=boca
            - DB_USER=boca
            - DB_PASSWORD=boca
            - ADMIN_USER=admin
            - ADMIN_PASSWORD=algochallenger
