version: '3.7'
services:
    backend:
        hostname: backend
        image: jvfazolo/algochallenger-backend
#        build: 
#            context: ./backend
#            dockerfile: ./docker/Dockerfile
        volumes:
            - ~/boca/algochallenger/boca-volume:/var/www/app/storage
        depends_on:
            - db
        deploy:
           placement:
             constraints: [node.role == manager]
           replicas: 1
        ports:
            - 8001:80
        environment:
            - DB_CONNECTION=pgsql
            - APP_DEBUG=true
            - APP_URL=http://ip172-18-0-43-buqqjmvp2ffg00dr7mng-8001.direct.labs.play-with-docker.com
            - DB_PORT=5432
            - DB_DATABASE=boca
            - APP_NAME=Boca
            - LOG_CHANNEL=daily
            - DB_USERNAME=boca
            - APP_ENV=local
            - DB_PASSWORD=boca
            - DB_HOST=db
            - JWT_SECRET=UiUT2Dd8EwuiHpEFKsf93k945OTipS8uZb0gIl7PnwiVUIZv37yf5puWF0S5qHQx
            - APP_KEY=iUT2Dd8EwuiHpEFKs

    frontend:
        hostname: frontend
        image: jvfazolo/algochallenger-frontend
 #       build: 
 #           context: ./frontend
 #           dockerfile: ./docker/Dockerfile
        deploy:
           mode: global
           placement:
              constraints: [node.role == manager]
        environment: 
            - VUE_APP_BACKEND_URL=http://localhost:8001/api
        ports: 
            - 8181:80
        depends_on: 
            - backend

    db:
        image: postgres:12
        hostname: db
        environment:
            - POSTGRES_PASSWORD=boca
            - POSTGRES_USER=boca
       # healthcheck:
       #     test: ["CMD-SHELL", "pg_isready -U postgres"]
       #     interval: 10s
       #     timeout: 5s
       #     retries: 5
        deploy:
           placement:
             constraints: [node.role == manager]

    boca-jail:
        image: jvfazolo/boca-jail
        hostname: boca-jail
        depends_on:
            - db
        deploy:
           replicas: 1
           resources:
             limits:
               cpus: '0.5'
               memory: 512M
        environment:
            - API_URL=http://backend/api
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=boca
            - DB_USER=boca
            - DB_PASSWORD=boca
            - ADMIN_USER=admin
            - ADMIN_PASSWORD=algochallenger
